// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ScrollerController from "./scroller_controller"
application.register("scroller", ScrollerController)

import LocationsAutocompleteController from "./locations_autocomplete_controller"
application.register("locations-autocomplete", LocationsAutocompleteController)

import MapController from "./map_controller"
application.register("map", MapController)
